name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_database: ^10.5.4
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  equatable: ^2.0.5
  card_swiper: ^3.0.1
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.9
  day_night_switcher: ^0.2.0+1
  slide_switcher: ^1.1.2
  animated_toggle_switch: ^0.8.2
  # Navigation page transition
  page_transition: ^2.1.0
  # file picker
  file_picker: ^8.0.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/auth/image/
    - assets/home/
    - assets/profile/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
