// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9yQaxhrkl241bcg6HnZOM9Yfm3b7nNe8',
    appId: '1:628322936073:web:031b1714ca4d7905991fd8',
    messagingSenderId: '628322936073',
    projectId: 'my-app-f4503',
    authDomain: 'my-app-f4503.firebaseapp.com',
    storageBucket: 'my-app-f4503.appspot.com',
    measurementId: 'G-46FRZ5GDJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8bJfkworHUC8EGJ8ELGj9e3quTqh_Wxc',
    appId: '1:628322936073:android:c26da16503b1fd98991fd8',
    messagingSenderId: '628322936073',
    projectId: 'my-app-f4503',
    storageBucket: 'my-app-f4503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3O_qmfd6aFL4TWA6twCycXKn8qnWVZ9c',
    appId: '1:628322936073:ios:340430ed25c6603c991fd8',
    messagingSenderId: '628322936073',
    projectId: 'my-app-f4503',
    storageBucket: 'my-app-f4503.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3O_qmfd6aFL4TWA6twCycXKn8qnWVZ9c',
    appId: '1:628322936073:ios:340430ed25c6603c991fd8',
    messagingSenderId: '628322936073',
    projectId: 'my-app-f4503',
    storageBucket: 'my-app-f4503.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9yQaxhrkl241bcg6HnZOM9Yfm3b7nNe8',
    appId: '1:628322936073:web:b4fea238ba703aa3991fd8',
    messagingSenderId: '628322936073',
    projectId: 'my-app-f4503',
    authDomain: 'my-app-f4503.firebaseapp.com',
    storageBucket: 'my-app-f4503.appspot.com',
    measurementId: 'G-7TKHPLJGL6',
  );

}